[window]
padding = { x = 16, y = 16 }

[font]
size = 13

[font.bold]
family = "Gintronic"
style = "Bold"

[font.bold_italic]
family = "Gintronic"
style = "Bold Italic"

[font.italic]
family = "Gintronic"
style = "Italic"

[font.normal]
family = "Gintronic"
style = "Regular"
